### ISSUE TITLE
API changes

### ISSUE THREAD

**Issue by gen2brain** [TheForgotten69/go-opensubtitles#12]
It looks like the API at https://opensubtitles.stoplight.io/docs/opensubtitles-api/e3750fd63a100-getting-started has been changed, or it was still not final when this Go library was made. Now there are `/features` and `/subtitles` endpoints but there are no `/find` and `/search` that this library uses.

**Comment by antonsoroko** [comment]
Yeah, looks like they introduced many small changes. I also wanted to use this package, but i had to fix it first.
It works now. Also, I added more comprehensive example.
Also i must note that unfortunately this is not an OOP style package. Some refactoring would be beneficial.
