### ISSUE TITLE
Full ability to upload subtitles

### ISSUE THREAD

**Issue by superbonaci** [TheForgotten69/go-opensubtitles#4]
Feature request: ability to upload subtitles to opensubtitles, like [OpenSubtitles Uploader](https://github.com/vankasteelj/opensubtitles-uploader), which hasn't been updated in a while and doesn't work anymore.

**Comment by opensubtitles** [comment]
actually it works without any problem, and new API doesnt support uploads (yet)

**Comment by superbonaci** [comment]
Right it works now.
